# Autogenerated file
def render(info):
    yield """
      <form name='frmselect' method='post'>
         <table>
            <TR>
               <TD colspan='2'>
                  <h2>Main Settings</h2>
            <TR>
               <TD>Unit Name:
               <TD><input type='text' name='name' maxlength=25 value='"""
    yield str(info['name'])
    yield """'>
            <TR>
               <TD>Webserver Port:
               <TD><input type='number' name='port' min=1 max=65535 value="""
    yield str(info['port'])
    yield """> <a class=\"button help\" href=\"\" target=\"_blank\">&#10068;</a>
            <TR>
               <TD>Unit Number:
               <TD><input type='number' name='unit' min=0 max=9999 style='width:5em;' value="""
    yield str(info['unit'])
    yield """>
            <TR>
               <TD>Admin Password:
               <TD><input type='password' name='password' maxlength=25 value='"""
    yield str(info['password'])
    yield """'>
            <TR>
               <TD colspan='2'>
                  <h3>Wifi Settings</h3>
            <TR>
               <TD>Select wifi mode: 
               <TD><select name='mode' """
    yield str(info['wifi'])
    yield """>
                  <option value=\"STA\" """
    if info["mode"] == "STA":
        yield """selected"""
    yield """>Station</option>
                  <option value=\"STA+AP\" """
    if info["mode"] == "STA+AP":
        yield """selected"""
    yield """>Station and Access Point</option>
                  <option value=\"AP\" """
    if info["mode"] == "AP":
        yield """selected"""
    yield """>Access Point</option>
               </select>
            <TR>
               <TD>SSID:
               <TD><input type='text' name='ssid' maxlength=31 value='"""
    yield str(info['ssid'])
    yield """' """
    yield str(info['wifi'])
    yield """>
            <TR>
               <TD>WPA Key:
               <TD><input type='password' name='key' maxlength=63 value='"""
    yield str(info['key'])
    yield """' """
    yield str(info['wifi'])
    yield """>
            <TR>
               <TD>Fallback SSID:
               <TD><input type='text' name='fbssid' maxlength=31 value='"""
    yield str(info['fbssid'])
    yield """' """
    yield str(info['wifi'])
    yield """>
            <TR>
               <TD>Fallback WPA Key:
               <TD><input type='password' name='fbkey' maxlength=63 value='"""
    yield str(info['fbkey'])
    yield """' """
    yield str(info['wifi'])
    yield """>
            <TR>
               <TD colspan='2'>
                  <hr>
            <TR>
               <TD colspan='2'>
                  <h3>IP Settings</h3>
            <TR>
               <TD>IP:
               <TD><input type='text' name='ip' value='"""
    yield str(info['ip'])
    yield """' """
    yield str(info['ethernet'])
    yield """>
            <TR>
               <TD>GW:
               <TD><input type='text' name='gateway' value='"""
    yield str(info['gateway'])
    yield """' """
    yield str(info['ethernet'])
    yield """>
            <TR>
               <TD>Subnet:
               <TD><input type='text' name='subnet' value='"""
    yield str(info['subnet'])
    yield """' """
    yield str(info['ethernet'])
    yield """>
            <TR>
               <TD>DNS:
               <TD><input type='text' name='dns' value='"""
    yield str(info['dns'])
    yield """' """
    yield str(info['ethernet'])
    yield """>
            <TR>
               <TD>
               <TD>
                  <div class='note'>Note: Leave empty for DHCP</div>
            <TR>
               <TD colspan='2'>
                  <h3>Sleep Mode</h3>
            <TR>
               <TD>Sleep enabled:
               <TD><input type=checkbox id='sleepenable' name='sleepenable' """
    yield str(info['sleepenable'])
    yield """ """
    yield str(info['sleep'])
    yield """> <a class=\"button help\" href=\"\" target=\"_blank\">&#10068;</a>
            <TR>
               <TD>Sleep Delay:
               <TD><input type='number' name='sleeptime' min=0 max=4294 style='width:5em;' value="""
    yield str(info['sleeptime'])
    yield """ """
    yield str(info['sleep'])
    yield """> [sec]
            <TR>
               <TD>Sleep on connection failure:
               <TD><input type=checkbox id='sleepfailure' name='sleepfailure' """
    yield str(info['sleepfailure'])
    yield """ """
    yield str(info['sleep'])
    yield """>
            <TR>
               <TD colspan='2'>
                  <hr>
            <TR>
               <TD>
               <TD><input class='button link' type='submit' value='Submit'>
         </table>
      </form>

"""
