# Autogenerated file
def render(info,controllers):
    yield """
<script type=\"text/javascript\">
function controllerDelete(id) """
    yield """{
  $.ajax("""
    yield """{
    url: \"/api/v1.0/controller/\" + id,
    type: 'DELETE',
    success: function (product) """
    yield """{
      $(ctl).parents(\"tr\").remove();
    },
    error: function (request, message, error) """
    yield """{
      handleException(request, message, error);
    }
  });
}
</script>
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TH>
       <TH>ID
       <TH>Protocol
       <TH>Hostname
       <TH>Port
       <TH>Enabled
       <TH>
       """
    for controller in controllers:
        yield """
           """
        if controller['id'] != 0:
            yield """ 
           <TR>
              <TD><a class=\"button link\" href=\"/controller_setting?id="""
            yield str(controller['id'])
            yield """\">Edit</a>
              <TD>"""
            yield str(controller['id'])
            yield """
              <TD>"""
            yield str(controller['protocol'])
            yield """
              <TD>"""
            yield str(controller['hostname'])
            yield """
              <TD>"""
            yield str(controller['port'])
            yield """
              <TD><span style=\"color:"""
            if controller['enable']=='on':
                yield """green"""
            else:
                yield """red"""
            yield """\">"""
            if controller['enable']=='on':
                yield """Yes"""
            else:
                yield """No"""
            yield """</span>
              <TD><a class=\"button link\" onclick=\"controllerDelete("""
            yield str(controller['id'])
            yield """);\">Del</a>
           """
        yield """
       """
    yield """
       <TR>
          <TD><a class=\"button link\" href=\"/controller_setting?id=0\">Add</a>
          <TD colspan=\"5\">
    </table>
"""
