# Autogenerated file
def render(info,controller):
    yield """
          <TR>
             <TD>Enabled:
             <TD><input type=checkbox id='enable' name='enable' """
    if controller['enable'] == 'on':
        yield """checked"""
    yield """>
          <TR>
             <TD colspan='2'>
                <hr>
          <TR>
             <TD>
             <TD><a class=\"button link\" href=\"controllers\">Close</a><input class=\"button link\" type='submit' value='Submit'>
       </table>
    </form>
"""
