# Autogenerated file
def render(info,protocol):
    yield """
    <form name='frmselect' method='post'>
       <table>
          <TH>Controller Settings
          <TH>
          <TR>
             <TD>Protocol:
             <TD style=\"font-size: 12pt; font-weight: bold; color: blue\">"""
    yield str(protocol['name'])
    yield """
             <input type='hidden' name='protocol' value='"""
    yield str(protocol["name"])
    yield """'>
"""
