# Autogenerated file
def render(info,protocols,controller):
    yield """
         <TR>
             <TD>Locate Controller:
             <TD>
                <select name='usedns'>
                   <option value='off' """
    if controller['usedns'] == '':
        yield """selected"""
    yield """>Use IP address</option>
                   <option value='on' """
    if controller['usedns'] ==  'on':
        yield """selected"""
    yield """>Use Hostname</option>
                </select>
          <TR>
             <TD>Controller Hostname:
             <TD><input type='text' name='hostname' maxlength='64' value='"""
    yield str(controller['hostname'])
    yield """'>
          <TR>
             <TD>Controller Port:
             <TD><input type='number' name='port' min='1' max='65535' style='width: 80px;' value='"""
    yield str(controller['port'])
    yield """'>
          <TR>
             <TD>Controller User:
             <TD><input type='text' name='user' maxlength='26' value='"""
    yield str(controller['user'])
    yield """'>
          <TR>
             <TD>Controller Password:
             <TD><input type='password' name='password' maxlength='64' value='"""
    yield str(controller['password'])
    yield """'>
          <TR>
             <TD>Controller Subscribe:
             <TD><input type='text' name='subscribe' maxlength='64' value='"""
    yield str(controller['subscribe'])
    yield """'>
          <TR>
             <TD>Controller Publish:
             <TD><input type='text' name='publish' maxlength='64' value='"""
    yield str(controller['publish'])
    yield """'>
"""
