# Autogenerated file
def render(info, hardware, dx_label, dxpin):
    yield """
   <script type=\"text/javascript\">
    function copyDiv() """
    yield """{
        selectHTML = `<select name='dx'>
               <option value='0'>Off</option>
               <option value='1'>Input</option>
               <option value='2'>Output Pull None</option>
               <option value='3'>Output Pull Up</option>
               <option value='4'>Output Pull Down</option>
               <option value='5'>Output Open Drain</option>
               <option value='6'>Output Alt Pull Up</option>
               <option value='7'>Output Alt Pull Down</option>
               <option value='8'>Disabled</option>
            </select>`;
        """
    for cnt in range(0,dx_label["count"]):
        yield """
            """
        dstr = 'd{}'.format(cnt)
        yield """
            document.getElementById('"""
        yield str(dstr)
        yield """').innerHTML = selectHTML.replace(/dx/,\""""
        yield str(dstr)
        yield """\");
            document.querySelector('#"""
        yield str(dstr)
        yield """ [value=\"' + document.getElementById('"""
        yield str(dstr)
        yield """').getAttribute(\"dxpin\") + '\"]').selected = true;
            if (document.getElementById('"""
        yield str(dstr)
        yield """').getAttribute(\"disabled\") ) """
        yield """{
                $(\"#"""
        yield str(dstr)
        yield """\").children().attr(\"disabled\",\"disabled\");            }
        """
    yield """
    };
        
    $(document).ready(function()"""
    yield """{
        // Copies all contents of boardled select into all other selects
        copyDiv();
   });
   </script>
   <form  method='post'>
   <table>
      <TH>Pin BootState Settings
      <TH>
      <TR>
         <TD colspan='2'>
            <h3>Dx boot states</h3>
         """
    for cnt in range(0,dx_label["count"]):
        yield """
         """
        dstr = 'd{}'.format(cnt)
        yield """
      <TR>
         <TD>Pin mode """
        yield str(dx_label[dstr])
        yield """:
         <TD>
            <div id=\""""
        yield str(dstr)
        yield """\" dxpin=\""""
        yield str(hardware[dstr])
        yield """\" disabled=\""""
        yield str(dxpin[dstr])
        yield """\">
            </div>
         """
    yield """
      <TR>
         <TD colspan='2'>
            <hr>
      <TR>
         <TD colspan='2'><a class=\"button link\" href=\"hardware\">Close</a><input class=\"button link\" type='submit' value='Submit'>
      <TR>
         <TD>
   </table>
</form>
"""
