# Autogenerated file
def render(info,dxpin,hardware, dx_label):
    yield """
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TH>Dx
       <TH>In/Out
       <TH>State
       <TH>Reserved by
       """
    for cnt in range(0, dx_label["count"]):
        yield """
       <TR>
          <td class=\"pin\">"""
        yield str(dx_label['d'+str(cnt)])
        yield """
          <TD>"""
        if hardware['d'+str(cnt)] == 0:
            yield """Off"""
        yield """
              """
        if hardware['d'+str(cnt)] == 1:
            yield """Input"""
        yield """
              """
        if hardware['d'+str(cnt)] == 2:
            yield """Output Pull None"""
        yield """
              """
        if hardware['d'+str(cnt)] == 3:
            yield """Output Pull Up"""
        yield """
              """
        if hardware['d'+str(cnt)] == 4:
            yield """Output Pull Down"""
        yield """
              """
        if hardware['d'+str(cnt)] == 5:
            yield """Output Open Drain"""
        yield """
              """
        if hardware['d'+str(cnt)] == 6:
            yield """Output Alt Pull Up"""
        yield """
              """
        if hardware['d'+str(cnt)] == 7:
            yield """Output Alt Pull Down"""
        yield """
              """
        if hardware['d'+str(cnt)] == 8:
            yield """Disabled"""
        yield """
          <TD align=\"center\">"""
        if hardware['d'+str(cnt)] != 1:
            yield """-"""
        yield """
          <TD>"""
        yield str(dxpin['d'+str(cnt)])
        yield """
       """
    yield """
       <TR>
          <TD colspan=\"2\"><a class=\"button link\" href=\"/tools\">close</a>
          <TD>
          <TD><a class=\"button link\" href=\"/dxpins\">reload</a>
    </table>
"""
