# Autogenerated file
def render(info, file):
    yield """
<form name = 'frmselect' method = 'post'>
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TH>Name
       <TR>
            <TD>
            """
    if file['operation'] == 'edit':
        yield """ 
                <B>"""
        yield str(file['filename'])
        yield """</B>
                <input type='hidden' name='filename' maxlength='26' value='"""
        yield str(file['filename'])
        yield """'>
            """
    else:
        yield """
                Filename: <input type='text' name='filename' maxlength='26' value=''>
            """
    yield """
       <TR>
          <TD><textarea name='content' rows='15' cols='80' wrap='on'>"""
    yield str(file['content'])
    yield """</textarea>
       <TR>
          <TD>Current size: """
    yield str(file['size'])
    yield """ characters
       <TR>
          <TD>
            <hr>
       <TR>
          <TD><a class=\"button link\" href=\"files\">Close</a><input class=\"button link\" type='submit' value='Submit'>
   </table>
</form>
"""
