# Autogenerated file
def render(info, files):
    yield """
<form name = 'frmselect' method = 'post'>
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TH>Name
       <TH width=\"30\">
       <TH width=\"30\">
       <TH width=\"30\">
        """
    if info["rootdir"] == 'N':
        yield """
               <TR>
                    <TD style=\"font-size: 12pt; font-weight: bold;\" >[<a style=\"font-size: 12pt; font-weight: bold;\" href=\"/files?name=..\">..</a>]
                    <TD>
                    <TD>
                    <TD>
        """
    yield """
        """
    for file in files:
        yield """
            """
        if file[0] != '.' and file[0] != '..' and (file[1] == 4 or file[1] == 16384):
            yield """
               <TR>
                    <TD style=\"font-size: 12pt; font-weight: bold;\">[<a style=\"font-size: 12pt; font-weight: bold;\" href=\"/files?name="""
            yield str(file[0])
            yield """\">"""
            yield str(file[0])
            yield """</a>]
                    <TD><a class=\"button link\" href=\"/file_setting?name="""
            yield str(file[0])
            yield """&oper=edit\">Edit</a>
                    <TD><a class=\"button link\" href=\"/file_setting?name="""
            yield str(file[0])
            yield """&oper=del&ftype=dir\">Del</a>
                    <TD>
            """
        yield """
        """
    yield """            
        """
    for file in files:
        yield """
            """
        if file[1] == 8 or file[1] == 32768:
            yield """
               <TR>
                    <TD style=\"font-size: 12pt; font-weight: bold;\">"""
            yield str(file[0])
            yield """
                    <TD><a class=\"button link\" href=\"/file_setting?name="""
            yield str(file[0])
            yield """&oper=edit\">Edit</a>
                    <TD><a class=\"button link\" href=\"/file_setting?name="""
            yield str(file[0])
            yield """&oper=del&ftype=file\">Del</a>
                    <TD><a class=\"button link\" href=\"/file_setting?name="""
            yield str(file[0])
            yield """&oper=download\">Download</a>
            """
        yield """
        """
    yield """            
       <TR>
          <TD colspan=\"4\"><a class=\"button link\" href=\"/file_setting?oper=add\">Add</a>
   </table>
</form>
"""
