# Autogenerated file
def render(i2clist):
    yield """
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TH>I2C Address
       <TH>Plugin
       """
    for i2c in i2clist:
        yield """
           <TR>
              <TD>"""
        yield str(hex(i2c))
        yield """
              <TD>
       """
    yield """
       <TR>
          <TD><a class=\"button link\" href=\"/tools\">close</a>
          <TD><a class=\"button link\" href=\"/tools?ucmd=i2cscanner\">reload</a>
    </table>
"""
