# Autogenerated file
def render(info):
    yield """      <form>
         <table>
            <TR>
               <TH>System Info
               <TH>Value
            <TR>
               <TD>Unit
               <TD>"""
    yield str(info['unit'])
    yield """
            <TR>
               <TD>Platform
               <TD>"""
    yield str(info['platform'])
    yield """
            <TR>
               <TD>Version
               <TD>"""
    yield str(info['version'])
    yield """
            <TR>
               <TD>Build Status
               <TD>"""
    yield str(info['buildstatus'])
    yield """
            <TR>
               <TD>Build Version
               <TD>"""
    yield str(info['buildversion'])
    yield """
            <TR>
               <TD>Database Version
               <TD>"""
    yield str(info['dbversion'])
    yield """
            <TR>
               <TD>Micropython Version
               <TD>"""
    yield str(info['micropython'])
    yield """
            <TR>
               <TD>Machine Board
               <TD>"""
    yield str(info['board'])
    yield """
            <TR>
               <TD>Unique Identifier
               <TD>"""
    yield str(info['unique'])
    yield """
            <TR>
               <TD>CPU Frequency
               <TD>"""
    yield str(info['unique'])
    yield """
           <TR>
               <TD colspan='2'>
                  <hr>
                  <B>TIME</B>
            <TR>
               <TD>Local Time
               <TD>"""
    yield str(info['time'])
    yield """
            <TR>
               <TD>Uptime
               <TD>"""
    yield str(info['uptime'])
    yield """
            <TR>
               <TD colspan='2'>
                  <hr>
                  <B>Network</B>
            <TR>
               <TD>IP
               <TD>"""
    yield str(info['ip'])
    yield """
            <TR>
               <TD>Gateway
               <TD>"""
    yield str(info['gateway'])
    yield """
            <TR>
               <TD>Netmask
               <TD>"""
    yield str(info['subnet'])
    yield """
            <TR>
               <TD>DNS
               <TD>"""
    yield str(info['dns'])
    yield """
            <TR>
               <TD colspan='2'>
                  <hr>
                  <B>Memory</B>
            <TR>
               <TD>Free Heap
               <TD>"""
    yield str(info['free'])
    yield """
            <TR>
               <TD>Total Heap
               <TD>"""
    yield str(info['total'])
    yield """
             <TR>
               <TD>Current Use Heap
               <TD>"""
    yield str(info['current'])
    yield """
            <TR>
               <TD>Peak Use Heap
               <TD>"""
    yield str(info['peak'])
    yield """
            <TR>
               <TD>Used Stack 
               <TD>"""
    yield str(info['stack'])
    yield """
            <TR>
               <TD colspan='2'>
                  <hr>
           <TR>
            <TD colspan='2'><a class=\"button link\" href=\"/tools\">close</a>
         </table>
      </form>
"""
