# Autogenerated file
def render(info):
    yield """
<form enctype=\"multipart/form-data\" method=\"post\">
   <p>Load settings file:<br><input type=\"file\" name=\"datafile\" size=\"40\"></p>
   <div><input class=\"button link\" type='submit' value='Load'></div>
</form>"""
