# Autogenerated file
def render(info, plugins):
    yield """
<form name='frmselect' method='post'>
<table>
<TH>Device Plugin
<TH>Value
<TR>
   <TD>PlugIn:
   <TD>
      <select name='pluginid'>
      """
    for plugin in plugins:
        yield """
      <option value='"""
        yield str(plugin["id"])
        yield """'>"""
        yield str(plugin["name"])
        yield """</option>
      """
    yield """
      </select>
      <input type='hidden' name='id' maxlength='40' value='0'>
      <a class=\"button link\" href=\"\" target=\"_blank\">?</a>
    <TR>
       <TD>
       <TD><a class=\"button link\" href=\"devices\">Close</a><input class=\"button link\" type='submit' value='Submit'>
</table>
</form>
"""
