# Autogenerated file
def render(info, controllers, plugins, plugindata, device, dxpin, dx_label, hardware):
    yield """
<form name='frmselect' method='post'>
<table>
<TH>Device Setting
<TH>Value
<TR>
   <TD>PlugIn:
   <TD style=\"font-size: 12pt; font-weight: bold; color: blue\">"""
    yield str(info["pluginname"])
    yield """
<TR>
   <TD>Name:
   <TD><input type='text' name='name' maxlength='40' value='"""
    yield str(device["name"])
    yield """'>
<TR>
   <TD>Delay:
   <TD><input type='number' name='delay' min=0 max=86400 style='width: 80px;' value='"""
    yield str(device["delay"])
    yield """'> (sec)
"""
    if plugindata["pincnt"] > 0:
        yield """
"""
        for dxcnt in range(0,plugindata["pincnt"]):
            yield """
<TR>
   <TD>Dx Pin """
            yield str(dxcnt+1)
            yield """:
   <TD>
      <select name='dxpin"""
            yield str(str(dxcnt))
            yield """'>
      """
            for cnt in range(0, dx_label["count"]):
                yield """
      <option value='d"""
                yield str(cnt)
                yield """' """
                if hardware['d'+str(cnt)] == 8 or dxpin['d'+str(cnt)] != '':
                    yield """disabled"""
                if device["dxpin"+str(dxcnt)] == 'd'+str(cnt):
                    yield """ selected"""
                yield """>"""
                yield str(dx_label['d'+str(cnt)])
                yield """</option>
      """
            yield """
      </select>
"""
        yield """
"""
    yield """
"""
    if device["i2c"] > 0:
        yield """
<TR>
   <TD>I2C:
   <TD>
      <select name='i2c'>
         <option value=1 """
        if device['i2c'] == 1:
            yield """selected"""
        yield """>1 - (default)</option>
      </select>
"""
    yield """
"""
    if device["spi"] > 0:
        yield """
<TR>
   <TD>SPI:
   <TD>
      <select name='spi'>
         <option value=1 """
        if device['spi'] == 1:
            yield """selected"""
        yield """>1 - (default)</option>
      </select>
"""
    yield """
"""
    if device["uart"] > 0:
        yield """
<TR>
   <TD>UART:
   <TD>
      <select name='uart'>
         <option value=1 """
        if device['uart'] == 1:
            yield """selected"""
        yield """>1 - (default)</option>
      </select>
"""
    yield """
<TR>
   <TD>Pull UP:
   <TD><input type=checkbox id='pullup' name='pullup' """
    if device["pullup"] == 'on':
        yield """checked"""
    yield """>
<TR>
   <TD>Inversed:
   <TD><input type=checkbox id='inverse' name='inverse' """
    if device["inverse"] == 'on':
        yield """checked"""
    yield """>
<TR>
   <TD>Send Boot state:
   <TD><input type=checkbox id='bootstate' name='bootstate' """
    if device["bootstate"] == 'on':
        yield """checked"""
    yield """>
<TR>
   <TD>Send Data to controller
   <TD><select name='controller'>
      <option value='0' """
    if device["controller"] == 0:
        yield """selected"""
    yield """>- None -</option>
      """
    for controller in controllers:
        yield """
      <option value='"""
        yield str(controller["id"])
        yield """' """
        if int(controller["id"]) == device["controller"]:
            yield """selected"""
        yield """>"""
        yield str(controller["protocol"])
        yield """ - """
        yield str(controller["hostname"])
        yield """</option>
      """
    yield """
      </select>
      ID: <input type='number' name='controllerid' style='width: 80px;' value='"""
    yield str(device["controllerid"])
    yield """'>
<TR>
   <TD>Global Sync:
   <TD><input type=checkbox id='sync' name='sync'"""
    if device["sync"] == 'on':
        yield """checked"""
    yield """>
<TR>
   <TD>Enabled:
   <TD><input type=checkbox id='enable' name='enable' """
    if device["enable"] == 'on':
        yield """checked"""
    yield """>
<TR>
   <TH>Sensor Setting
   <TH>Value
"""
