# Autogenerated file
def render(info, rules):
    yield """
<form name = 'frmselect' method = 'post'>
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TH width=\"30\">
       <TH>Name
       <TH>Status
       <TH>
       <TH>
        """
    for rule in rules:
        yield """
           <TR>
                <TD><a class=\"button link\" href=\"/rule_setting?id="""
        yield str(rule["id"])
        yield """&oper=edit\">Edit</a>
                <TD style=\"font-size: 12pt; font-weight: bold;\" >"""
        yield str(rule["name"])
        yield """
                <TD style=\"font-size: 12pt; font-weight: bold;\" ><span style=\"color:"""
        if rule['enable'] == 'on':
            yield """Green"""
        else:
            yield """Red"""
        yield """\">"""
        yield str(rule["enable"])
        yield """
                <TD><a class=\"button link\" href=\"/rule_setting?id="""
        yield str(rule["id"])
        yield """&oper=del\">Del</a>
                <TD><a class=\"button link\" href=\"/rule_setting?id="""
        yield str(rule["id"])
        yield """&oper=enable\">On/Off</a>
        """
    yield """            
       <TR>
          <TD colspan=\"3\"><a class=\"button link\" href=\"/rule_setting?oper=add\">Add</a>
          <TD colspan=\"2\"><a class=\"button link\" href=\"/rule_setting?oper=refresh\">Refresh</a>
   </table>
</form>
"""
