# Autogenerated file
def render(info, scripts):
    yield """
<form name = 'frmselect' method = 'post'>
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TH width=\"30\">
       <TH>Name
       <TH width=\"30\">
        """
    for script in scripts:
        yield """
            """
        if script[0] != '..' and script[0] != '.' and script[0] != '__init__.py':
            yield """ 
               <TR>
                    <TD><a class=\"button link\" href=\"/script_setting?name="""
            yield str(script[0])
            yield """&oper=edit\">Edit</a>
                    <TD>"""
            yield str(script[0])
            yield """
                    <TD><a class=\"button link\" href=\"/script_setting?name="""
            yield str(script[0])
            yield """&oper=del\">Del</a>
            """
        yield """
        """
    yield """            
       <TR>
          <TD colspan=\"3\"><a class=\"button link\" href=\"/script_setting?oper=add\">Add</a>
   </table>
</form>
"""
