# Autogenerated file
def render(wifilist):
    yield """
<form name = 'frmselect' method=\"post\">
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TR>
          <TD>Select SSID: <select name='ssid'>
          """
    for wifi in wifilist:
        yield """
          <option value=\""""
        yield str(wifi['ssid'])
        yield """\">"""
        yield str(wifi['ssid'])
        yield """</option>
          """
    yield """
          </select>
       <TR>
          <TD>Enter Password for Secured SSID: <input type='password' name='key' maxlength='30' value=''>
          <a class=\"button link\" href=\"\" target=\"_blank\">?</a>
       <TR>
          <TD><a class=\"button link\" href=\"/\">Close</a> 
          <input class=\"button link\" type='submit' value='Submit'>
   </table>
   <BR>
   <B><U>Available SSID's:</U></B>
   <BR>
   <table cellpadding='4' border='1' frame='box' rules='all'>
    <TR>
       <TH>SSID
       <TH>Channel
       <TH>Strength
       <TH>Security
       <TH>Visible
       """
    for wifi in wifilist:
        yield """
           <TR>
              <TD>"""
        yield str(wifi['ssid'])
        yield """
              <TD>"""
        yield str(wifi['channel'])
        yield """
              <TD>"""
        yield str(wifi['strength'])
        yield """ db
              <TD>"""
        yield str(wifi['security'])
        yield """
              <TD>"""
        yield str(wifi['hidden'])
        yield """
       """
    yield """
   </table>
</form>"""
