# Autogenerated file
def render(info, plugindata):
    yield """
<!- DO NOT CHANGE LINE ABOVE! -->
<TR>
   <TD>DHT Type:
   <TD>
      <select name='dhttype'>
         <option value=11 """
    if plugindata['dhttype'] == 11:
        yield """selected"""
    yield """>DHT 11</option>
         <option value=12"""
    if plugindata['dhttype'] == 12:
        yield """selected"""
    yield """>DHT 12</option>
         <option value=22"""
    if plugindata['dhttype'] == 22:
        yield """selected"""
    yield """>DHT 22</option>
      </select>
"""
    yield str(plugindata['content'])
