# Autogenerated file
def render(info,protocols,controller):
    yield """
    <form name='frmselect' method='post'>
       <table>
          <TH>Controller Settings
          <TH>
          <TR>
             <TD>Protocol:
             <TD>
                <select name='protocol' LANGUAGE=javascript onchange=\"return dept_onchange(frmselect)\">
                   """
    for protocol in protocols:
        yield """
                        <option value='"""
        yield str(protocol['name'])
        yield """' """
        if info['id'] == protocol['id']:
            yield """selected"""
        yield """>"""
        yield str(protocol['name'])
        yield """</option>
                   """
    yield """
                </select>
                <input type='hidden' name='currentprotocol' maxlength='64' value='"""
    yield str(info['protocolname'])
    yield """'>
                <a class=\"button link\" href=\"\" target=\"_blank\">?</a>
         <TR>
             <TD>Locate Controller:
             <TD>
                <select name='usedns'>
                   <option value='off' """
    if controller['usedns'] == '':
        yield """selected"""
    yield """>Use IP address</option>
                   <option value='on' """
    if controller['usedns'] ==  'on':
        yield """selected"""
    yield """>Use Hostname</option>
                </select>
          <TR>
             <TD>Controller Hostname:
             <TD><input type='text' name='hostname' maxlength='64' value='"""
    yield str(controller['hostname'])
    yield """'>
          <TR>
             <TD>Controller Port:
             <TD><input type='number' name='port' min='1' max='65535' style='width: 80px;' value='"""
    yield str(controller['port'])
    yield """'>
          <TR>
             <TD>Controller User:
             <TD><input type='text' name='user' maxlength='26' value='"""
    yield str(controller['user'])
    yield """'>
          <TR>
             <TD>Controller Password:
             <TD><input type='password' name='password' maxlength='64' value='"""
    yield str(controller['password'])
    yield """'>
          <TR>
             <TD>Controller Subscribe:
             <TD><input type='text' name='subscribe' maxlength='64' value='"""
    yield str(controller['subscribe'])
    yield """'>
          <TR>
             <TD>Controller Publish:
             <TD><input type='text' name='publish' maxlength='64' value='"""
    yield str(controller['publish'])
    yield """'>
          <TR>
             <TD>Enabled:
             <TD><input type=checkbox id='enable' name='enable' """
    if controller['enable'] == 'on':
        yield """checked"""
    yield """>
          <TR>
             <TD colspan='2'>
                <hr>
          <TR>
             <TD>
             <TD><a class=\"button link\" href=\"controllers\">Close</a><input class=\"button link\" type='submit' value='Submit'>
       </table>
    </form>
"""
