# Autogenerated file
def render(logger):
    yield """
      <table>
         <TR>
            <TH>Log
         <TR>
            <TD>"""
    yield str(logger['content'])
    yield """
         <TR>
            <TD><a class=\"button link\" href=\"/tools\">close</a>
      </table>
"""
