# Autogenerated file
def render(info, services, notification):
    yield """
<form name='frmselect' method='post'>
   <table>
      <TH>Notification Settings
      <TH>
      <TR>
         <TD>Service:
         <TD>
            <select name='serviceid' LANGUAGE=javascript onchange=\"return dept_onchange(frmselect)\">
               """
    for service in services:
        yield """
                  <option value='"""
        yield str(service['id'])
        yield """'"""
        if notification['serviceid'] == service['id']:
            yield """ selected"""
        yield """>"""
        yield str(service['name'])
        yield """</option>
               """
    yield """
            </select>
            <input type='hidden' name='currentserviceid' size=64 value='"""
    yield str(notification['serviceid'])
    yield """'>
            <a class=\"button link\" href=\"\" target=\"_blank\">?</a>
      <TR>
         <TD>Domain:
         <TD><input type='text' name='domain' size=64 value=''>
      <TR>
         <TD>Sender:
         <TD><input type='text' name='sender' size=64 value=''>
      <TR>
         <TD>Receiver:
         <TD><input type='text' name='receiver' size=64 value=''>
      <TR>
         <TD>Subject:
         <TD><input type='text' name='subject' size=64 value=''>
      <TR>
         <TD>Body:
         <TD><textarea name='body' rows='5' cols='80' size=512 wrap='off'></textarea>
      <TR>
         <TD>Enabled:
         <TD><input type=checkbox id='enable' name='enable' """
    if notification['enable'] == 'on':
        yield """checked"""
    yield """>
      <TR>
         <TD colspan='2'>
            <hr>
      <TR>
         <TD>
         <TD><a class=\"button ink\" href=\"notifications\">Close</a><input class=\"button link\" type='submit' value='Submit'>
   </table>
</form>"""
