# Autogenerated file
def render(wifilist):
    yield """
    <table cellpadding='4' border='1' frame='box' rules='all'>
       <TH>SSID
       <TH>Channel
       <TH>Strength
       <TH>Security
       <TH>Hidden
       """
    for wifi in wifilist:
        yield """
           <TR>
              <TD>"""
        yield str(wifi['ssid'])
        yield """
              <TD>"""
        yield str(wifi['channel'])
        yield """
              <TD>"""
        yield str(wifi['strength'])
        yield """ db
              <TD>"""
        yield str(wifi['security'])
        yield """
              <TD>"""
        yield str(wifi['hidden'])
        yield """
       """
    yield """
       <TR>
          <TD><a class=\"button link\" href=\"/tools\">close</a>
          <TD colspan=\"3\">
          <TD><a class=\"button link\" href=\"/tools?ucmd=wifiscanner\">reload</a>
    </table>
"""
